print("Please enter first row of numbers:")
numa = (input())
numa = numa.split()
print("Please enter second row of numbers:")
numb = (input())
numb = numb.split()
numc = set(numa) & set(numb)
print(list(numc))
